### ISSUE TITLE
[FEAT]: Add focus-animation (scale)

### ISSUE THREAD

**Issue by BerkeAras** [BerkeAras/WorkGroup#27]
## Feature Request

**Describe the Feature Request**
Add focus-animation for buttons/menu-items.

**Describe Preferred Solution**
Scale-Animation

**Describe Alternatives**
N/A

**Related Code**
Example:
```scss
transition: all .2s;
&:focus {
     transform: scale(.98);
}
```
**Additional Context**
N/A
